[package]
name = "query-rds-data"
version = "1.2.3"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2021"
categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[dependencies]
csv = "1.1.6"
exitfailure = "0.5.1"
futures = "0.3.21"
log = "0.4.14"
loggerv = "0.7.2"
rusoto_core = "0.47.0"
rusoto_rds = "0.47.0"
rusoto_secretsmanager = "0.47.0"
serde = "1.0.136"
serde_json = "1.0.79"
snafu = "0.6.10"

[dependencies.clap]
features = ["derive", "env", "cargo", "wrap_help"]
version = "3.0.14"

[dependencies.rusoto_rds_data]
version = "0.47.0"
features = ["serialize_structs"]

[dependencies.tokio]
version = "1.16.1"
features = ["macros", "rt-multi-thread"]
