[package]
name = "query-rds-data"
version = "2.0.2"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2021"
categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[dependencies]
aws-config = "1.0.1"
aws-sdk-rds = "1.1.0"
aws-sdk-rdsdata = "1.1.0"
aws-sdk-secretsmanager = "1.1.0"
aws-types = "1.0.1"
csv = "1.3.0"
exitfailure = "0.5.1"
futures = "0.3.29"
log = "0.4.20"
loggerv = "0.7.2"
serde_json = "1.0.108"
snafu = "0.7.5"

[dependencies.clap]
features = ["cargo", "derive", "env", "wrap_help"]
version = "4.4.8"

[dependencies.serde]
features = ["derive"]
version = "1.0.193"

[dependencies.tokio]
version = "1.34.0"
features = ["macros", "rt-multi-thread"]
