[package]
name = "query-rds-data"
version = "2.0.2"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2021"
categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[dependencies]
aws-config = "0.49.0"
aws-sdk-rds = "0.19.0"
aws-sdk-rdsdata = "0.19.0"
aws-sdk-secretsmanager = "0.19.0"
aws-types = "0.49.0"
csv = "1.1.6"
exitfailure = "0.5.1"
futures = "0.3.24"
log = "0.4.17"
loggerv = "0.7.2"
serde_json = "1.0.85"
snafu = "0.7.2"

[dependencies.clap]
features = ["cargo", "derive", "env", "wrap_help"]
version = "4.0.10"

[dependencies.serde]
features = ["derive"]
version = "1.0.145"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]
