[package]
name = "query-rds-data"
version = "0.3.4"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"

categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[badges]
travis-ci = { repository = "bruceadams/query-rds-data" }

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.6"
failure_derive = "0.1.6"
futures = "0.1.29"
log = "0.4.8"
stderrlog = "0.4.1"
rusoto_core = "0.41.0"
rusoto_rds = "0.41.0"
rusoto_rds_data = "0.41.0"
rusoto_secretsmanager =  "0.41.0"
tokio = "0.1.22"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.3.3"
