[package]
name = "query-rds-data"
version = "0.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.28"
quicli = "0.4.0"
rusoto_core = "0.40.0"
rusoto_rds = "0.40.0"
rusoto_rds_data = "0.40.0"
rusoto_secretsmanager =  "0.40.0"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.3.0"
