[package]
name = "query-rds-data"
version = "0.5.2"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"

categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[badges]
travis-ci = { repository = "bruceadams/query-rds-data" }

[dependencies]
csv = "1.1.3"
exitfailure = "0.5.1"
futures = "0.3.5"
log = "0.4.8"
loggerv = "0.7.2"
rusoto_core = "0.43.0"
rusoto_rds = "0.43.0"
rusoto_rds_data = "0.43.0"
rusoto_secretsmanager =  "0.43.0"
snafu = "0.6.8"
tokio = "0.2.20"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.3.14"
