[package]
name = "query-rds-data"
version = "2.0.1"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2021"
categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[dependencies]
aws-config = "0.46.0"
aws-sdk-rds = "0.16.0"
aws-sdk-rdsdata = "0.16.0"
aws-sdk-secretsmanager = "0.16.0"
aws-types = "0.46.0"
csv = "1.1.6"
exitfailure = "0.5.1"
futures = "0.3.21"
log = "0.4.17"
loggerv = "0.7.2"
serde_json = "1.0.82"
snafu = "0.7.1"

[dependencies.clap]
features = ["derive", "env", "cargo", "wrap_help"]
version = "3.2.15"

[dependencies.serde]
features = ["derive"]
version = "1.0.140"

[dependencies.tokio]
version = "1.21.0"
features = ["macros", "rt-multi-thread"]
