[package]
name = "query-rds-data"
version = "0.5.2"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"
categories = ["database", "command-line-utilities"]
description = "Query AWS RDS Data from the command line"
homepage = "https://github.com/bruceadams/query-rds-data"
keywords = ["aws", "cli", "database", "rds", "sql"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/query-rds-data"

[badges]
travis-ci = { repository = "bruceadams/query-rds-data" }

[dependencies]
clap = "3.0.0-beta.2"
csv = "1.1.5"
exitfailure = "0.5.1"
futures = "0.3.8"
log = "0.4.11"
loggerv = "0.7.2"
rusoto_core = "0.46.0"
rusoto_rds = "0.46.0"
rusoto_rds_data = "0.46.0"
rusoto_secretsmanager = "0.46.0"
snafu = "0.6.10"

[dependencies.tokio]
version = "1.0.1"
features = ["macros", "rt-multi-thread"]
